/**
 * PantryItem
 *
 * Matches the shape returned by GET /api/v1/pantry and POST /api/v1/pantry.
 *
 * Key differences from the old frontend-only type:
 *   - id is a UUID string, not a number
 *   - ingredient_name replaces name
 *   - quantity is a number (e.g. 1.5), unit is a separate nullable string
 *   - expiration_date is an ISO date string (e.g. "2024-12-31") or null
 *   - urgent is computed client-side in PantryContext from expiration_date
 */
export interface PantryItem {
  /** UUID from the backend — used for update/delete API calls */
  id: string;
  user_id: string;
  /** The human-readable ingredient name, e.g. "Whole Milk" */
  ingredient_name: string;
  /** Lowercase normalized name used for deduplication, e.g. "whole milk" */
  normalized_name: string | null;
  /** Numeric quantity, e.g. 1.5 */
  quantity: number;
  /** Unit of measurement, e.g. "gallon", "g", "count". Null if unspecified. */
  unit: string | null;
  /** Pantry category, e.g. "dairy", "produce". Null if uncategorized. */
  category: string | null;
  /** Where in the kitchen this is stored, e.g. "fridge". Null if unspecified. */
  location: string | null;
  /** Barcode string if item was added via scanner. Null if added manually. */
  barcode: string | null;
  /** ISO date string "YYYY-MM-DD" or null if no expiry set */
  expiration_date: string | null;
  /** ISO datetime string when item was added */
  added_date: string;
  last_updated: string;
  deleted: boolean;
  /**
   * Computed client-side in PantryContext — true when expiration_date is
   * within 3 days. Not sent to or stored by the backend.
   */
  urgent: boolean;
}

/**
 * Recipe
 *
 * Matches the shape returned by GET /api/v1/recipes/suggestions.
 * This is the "list view" shape — just enough data to render a card.
 * For the full recipe (ingredients, step-by-step instructions), see RecipeDetail.
 *
 * Note: match_percentage comes from the backend comparing the recipe's
 * ingredients against the user's current pantry items.
 */
export interface Recipe {
  /** UUID from the backend */
  id: string;
  /** Recipe display name, e.g. "Spaghetti Carbonara" */
  title: string;
  /** One-sentence summary of the dish, or null if not provided */
  description: string | null;
  /** 0–100: how many of the recipe's ingredients the user already has */
  match_percentage: number;
  /** e.g. "easy", "medium", "hard", or null */
  difficulty: string | null;
  /** e.g. "Italian", "Mexican", or null */
  cuisine_type: string | null;
  /** Minutes of prep work (chopping, measuring), or null if unknown */
  prep_time_minutes: number | null;
  /** Minutes of actual cooking, or null if unknown */
  cook_time_minutes: number | null;
}

/**
 * RecipeDetail
 *
 * Full recipe shape returned by GET /api/v1/recipes/:id and
 * POST /api/v1/recipes/generate. Includes ingredients and instructions.
 *
 * ingredient_list and instructions are stored as arbitrary dicts on the
 * backend (flexible schema for AI-generated content), so we type them
 * as Record<string, any>[].
 */
export interface RecipeDetail extends Recipe {
  user_id: string | null;
  /** Array of { name, quantity, unit } objects */
  ingredient_list: Record<string, any>[];
  /** Array of { step, text } objects */
  instructions: Record<string, any>[];
  servings: number;
  meal_type: string | null;
  /** True if generated by OpenAI, false if manually created */
  is_ai_generated: boolean;
  nutritional_info: Record<string, any> | null;
  is_public: boolean;
  usage_count: number;
  created_at: string;
  updated_at: string;
}

export interface GroceryItem {
  id: number;
  name: string;
  quantity: string;
  price: number;
  checked: boolean;
  category?: string;
}

export interface Meal {
  id: number;
  name: string;
  recipeId?: number;
  time?: string;
  ingredients?: string[];
}

export interface MealSchedule {
  day: string;
  date: string;
  meals: Meal[];
}

export interface DayOfWeek {
  day: string;
  date: string;
}

/**
 * ParsedReceiptItem
 *
 * Represents one line item parsed from a scanned receipt.
 * Returned by POST /api/v1/receipts/scan inside the line_items array.
 *
 * The `selected` field is frontend-only — it drives the checkboxes on
 * ReceiptConfirmScreen so the user can deselect items they don't want added.
 * It is never sent to the backend.
 */
export interface ParsedReceiptItem {
  /** Product name extracted from the receipt, e.g. "Organic Whole Milk" */
  item: string;
  /** Price per unit as shown on the receipt, e.g. 3.99 */
  price: number;
  /** How many of this item were purchased, e.g. 2 */
  quantity: number;
  /** Auto-detected category e.g. "dairy", "produce" — may be "pantry" if unknown */
  category: string;
  /**
   * Whether this item is checked on the confirm screen.
   * Defaults to true (all items selected). User can uncheck items they
   * don't want added to their pantry.
   * NOT sent to the backend.
   */
  selected: boolean;
}

// Statistics
export interface PantryStats {
  totalItems: number;
  categoriesCount: number;
  expiringSoonCount: number;
  expiringItems: PantryItem[];
}

export interface GroceryStats {
  totalPrice: number;
  checkedCount: number;
  remainingCount: number;
  monthlyAverage: number;
}

