"""
Unit Tests for Receipts Router

Test Coverage:
- Process receipt endpoint (POST /receipts/process)
- Confirm receipt endpoint (POST /receipts/confirm)
- Get receipts endpoint (GET /receipts)
- Get specific receipt endpoint (GET /receipts/:id)
- Delete receipt endpoint (DELETE /receipts/:id)
- Edge cases: invalid input, missing data, permissions
- Error handling: parsing errors, database errors
"""

import pytest
from fastapi.testclient import TestClient
from unittest.mock import Mock, patch, MagicMock
from datetime import datetime
import uuid

# Mock FastAPI app and dependencies
@pytest.fixture
def mock_app():
    from fastapi import FastAPI
    from app.routers import receipts

    app = FastAPI()
    app.include_router(receipts.router, prefix="/receipts")
    return app


@pytest.fixture
def client(mock_app, mock_db):
    from app.database import get_db
    mock_app.dependency_overrides[get_db] = lambda: mock_db
    yield TestClient(mock_app)
    mock_app.dependency_overrides.clear()


@pytest.fixture
def mock_db():
    return Mock()


@pytest.fixture
def mock_user_id(test_user_id):
    # Must match the user_id in the JWT token generated by conftest auth_headers fixture
    return test_user_id


@pytest.fixture
def sample_receipt_id():
    return str(uuid.uuid4())


# ============================================================
# PROCESS RECEIPT TESTS
# ============================================================


@patch('app.routers.receipts.get_db')
@patch('app.routers.receipts.ReceiptParser.parse_receipt_text')
def test_process_receipt_success(mock_parse, mock_get_db, client, mock_db, auth_headers):
    """Full context: Process valid receipt OCR text"""
    mock_get_db.return_value = mock_db

    # Mock parsed receipt data
    mock_parse.return_value = {
        'merchant_name': 'Walmart',
        'purchase_date': datetime(2025, 1, 15, 14, 30),
        'total_amount': 45.67,
        'currency': 'USD',
        'line_items': [
            {'item': 'Milk', 'price': 3.99, 'quantity': 2},
            {'item': 'Eggs', 'price': 4.49, 'quantity': 1}
        ],
        'confidence': 0.85
    }

    # Mock database operations
    mock_db.add = Mock()
    mock_db.commit = Mock()
    mock_db.refresh = Mock()

    response = client.post(
        "/receipts/process",
        json={"ocr_text": "WALMART\n12/25/2024\nMilk $3.99\nEggs $4.49\nTOTAL: $8.48"}
    , headers=auth_headers)

    assert response.status_code == 200
    data = response.json()
    assert data['merchant_name'] == 'Walmart'
    assert data['total_amount'] == 45.67
    assert len(data['line_items']) == 2
    assert data['confidence'] == 0.85
    assert 'receipt_id' in data


@patch('app.routers.receipts.get_db')
def test_process_receipt_empty_text(mock_get_db, client, mock_db, auth_headers):
    """Edge case: Empty OCR text should return 400"""
    mock_get_db.return_value = mock_db

    response = client.post(
        "/receipts/process",
        json={"ocr_text": ""}
    , headers=auth_headers)

    assert response.status_code == 400
    assert "cannot be empty" in response.json()['detail'].lower()


@patch('app.routers.receipts.get_db')
@patch('app.routers.receipts.ReceiptParser.parse_receipt_text')
def test_process_receipt_parse_error(mock_parse, mock_get_db, client, mock_db, auth_headers):
    """Error handling: Parsing failure should return 400"""
    mock_get_db.return_value = mock_db

    mock_parse.side_effect = ValueError("Invalid receipt format")

    response = client.post(
        "/receipts/process",
        json={"ocr_text": "invalid text"}
    , headers=auth_headers)

    assert response.status_code == 400
    assert "Invalid receipt format" in response.json()['detail']


@patch('app.routers.receipts.get_db')
@patch('app.routers.receipts.ReceiptParser.parse_receipt_text')
def test_process_receipt_database_error(mock_parse, mock_get_db, client, mock_db, auth_headers):
    """Error handling: Database error should return 500"""
    mock_get_db.return_value = mock_db

    mock_parse.return_value = {
        'merchant_name': 'Walmart',
        'purchase_date': datetime(2025, 1, 15),
        'total_amount': 10.0,
        'currency': 'USD',
        'line_items': [],
        'confidence': 0.5
    }

    mock_db.commit.side_effect = Exception("Database connection failed")

    response = client.post(
        "/receipts/process",
        json={"ocr_text": "WALMART\nTOTAL: $10"}
    , headers=auth_headers)

    assert response.status_code == 500
    assert "Failed to process receipt" in response.json()['detail']


# ============================================================
# CONFIRM RECEIPT TESTS
# ============================================================


@patch('app.routers.receipts.get_db')
@patch('app.routers.receipts.AnalyticsService.update_monthly_analytics')
def test_confirm_receipt_success(mock_analytics, mock_get_db, client, mock_db, mock_user_id, sample_receipt_id, auth_headers):
    """Full context: Confirm valid receipt and add to pantry"""
    mock_get_db.return_value = mock_db

    # Mock receipt from database
    mock_receipt = Mock()
    mock_receipt.id = uuid.UUID(sample_receipt_id)
    mock_receipt.user_id = uuid.UUID(mock_user_id)
    mock_receipt.merchant_name = 'Walmart'
    mock_receipt.purchase_date = datetime(2025, 1, 15)
    mock_receipt.total_amount = 10.0
    mock_receipt.currency = 'USD'
    mock_receipt.line_items = [
        {'item': 'Milk', 'price': 3.99, 'quantity': 2}
    ]
    mock_receipt.processed = False

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = mock_receipt
    mock_db.query.return_value = mock_query

    mock_db.add = Mock()
    mock_db.commit = Mock()

    response = client.post(
        "/receipts/confirm",
        json={"receipt_id": sample_receipt_id}
    , headers=auth_headers)

    assert response.status_code == 201
    data = response.json()
    assert data['status'] == 'success'
    assert data['items_added'] == 1
    assert mock_receipt.processed is True
    mock_analytics.assert_called_once()


@patch('app.routers.receipts.get_db')
def test_confirm_receipt_not_found(mock_get_db, client, mock_db, auth_headers):
    """Edge case: Receipt not found should return 404"""
    mock_get_db.return_value = mock_db

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = None
    mock_db.query.return_value = mock_query

    response = client.post(
        "/receipts/confirm",
        json={"receipt_id": str(uuid.uuid4())},
        headers=auth_headers
    )

    assert response.status_code == 404
    assert "not found" in response.json()['detail'].lower()


@patch('app.routers.receipts.get_db')
def test_confirm_receipt_wrong_user(mock_get_db, client, mock_db, mock_user_id, sample_receipt_id, auth_headers):
    """Edge case: Receipt belongs to different user should return 403"""
    mock_get_db.return_value = mock_db

    # Mock receipt from different user
    mock_receipt = Mock()
    mock_receipt.id = uuid.UUID(sample_receipt_id)
    mock_receipt.user_id = uuid.uuid4()  # Different user
    mock_receipt.processed = False

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = mock_receipt
    mock_db.query.return_value = mock_query

    response = client.post(
        "/receipts/confirm",
        json={"receipt_id": sample_receipt_id}
    , headers=auth_headers)

    assert response.status_code == 403
    assert "different user" in response.json()['detail'].lower()


@patch('app.routers.receipts.get_db')
def test_confirm_receipt_already_processed(mock_get_db, client, mock_db, mock_user_id, sample_receipt_id, auth_headers):
    """Edge case: Receipt already processed should return 409"""
    mock_get_db.return_value = mock_db

    mock_receipt = Mock()
    mock_receipt.id = uuid.UUID(sample_receipt_id)
    mock_receipt.user_id = uuid.UUID(mock_user_id)
    mock_receipt.processed = True  # Already processed

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = mock_receipt
    mock_db.query.return_value = mock_query

    response = client.post(
        "/receipts/confirm",
        json={"receipt_id": sample_receipt_id}
    , headers=auth_headers)

    assert response.status_code == 409
    assert "already been processed" in response.json()['detail'].lower()


@patch('app.routers.receipts.get_db')
@patch('app.routers.receipts.AnalyticsService.update_monthly_analytics')
def test_confirm_receipt_with_corrections(mock_analytics, mock_get_db, client, mock_db, mock_user_id, sample_receipt_id, auth_headers):
    """Full context: User corrects receipt data before confirming"""
    mock_get_db.return_value = mock_db

    mock_receipt = Mock()
    mock_receipt.id = uuid.UUID(sample_receipt_id)
    mock_receipt.user_id = uuid.UUID(mock_user_id)
    mock_receipt.merchant_name = 'Unknown'
    mock_receipt.purchase_date = datetime(2025, 1, 1)
    mock_receipt.total_amount = 5.0
    mock_receipt.currency = 'USD'
    mock_receipt.line_items = []
    mock_receipt.processed = False

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = mock_receipt
    mock_db.query.return_value = mock_query

    mock_db.add = Mock()
    mock_db.commit = Mock()

    response = client.post(
        "/receipts/confirm",
        json={
            "receipt_id": sample_receipt_id,
            "merchant_name": "Corrected Store",
            "purchase_date": "2025-01-15T14:30:00",
            "total_amount": 15.50,
            "line_items": [
                {"item": "Bread", "price": 3.99, "quantity": 1}
            ],
            "notes": "User correction"
        }
    , headers=auth_headers)

    assert response.status_code == 201
    assert mock_receipt.merchant_name == "Corrected Store"
    assert mock_receipt.total_amount == 15.50
    assert mock_receipt.notes == "User correction"
    assert len(mock_receipt.line_items) == 1


@patch('app.routers.receipts.get_db')
@patch('app.routers.receipts.AnalyticsService.update_monthly_analytics')
def test_confirm_receipt_empty_line_items(mock_analytics, mock_get_db, client, mock_db, mock_user_id, sample_receipt_id, auth_headers):
    """Edge case: Empty line items should still process successfully"""
    mock_get_db.return_value = mock_db

    mock_receipt = Mock()
    mock_receipt.id = uuid.UUID(sample_receipt_id)
    mock_receipt.user_id = uuid.UUID(mock_user_id)
    mock_receipt.merchant_name = 'Store'
    mock_receipt.purchase_date = datetime(2025, 1, 15)
    mock_receipt.total_amount = 0.0
    mock_receipt.currency = 'USD'
    mock_receipt.line_items = []
    mock_receipt.processed = False

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = mock_receipt
    mock_db.query.return_value = mock_query

    mock_db.commit = Mock()

    response = client.post(
        "/receipts/confirm",
        json={"receipt_id": sample_receipt_id}
    , headers=auth_headers)

    assert response.status_code == 201
    data = response.json()
    assert data['items_added'] == 0


# ============================================================
# GET RECEIPTS TESTS
# ============================================================


@patch('app.routers.receipts.get_db')
def test_get_receipts_success(mock_get_db, client, mock_db, auth_headers):
    """Full context: Get all user receipts"""
    mock_get_db.return_value = mock_db

    # Mock receipts
    mock_receipt1 = Mock()
    mock_receipt1.id = uuid.uuid4()
    mock_receipt1.merchant_name = 'Walmart'
    mock_receipt1.purchase_date = datetime(2025, 1, 15)
    mock_receipt1.total_amount = 50.0
    mock_receipt1.currency = 'USD'
    mock_receipt1.line_items = []
    mock_receipt1.processed = True
    mock_receipt1.created_at = datetime(2025, 1, 15)

    mock_query = Mock()
    mock_query.filter.return_value.order_by.return_value.limit.return_value.all.return_value = [mock_receipt1]
    mock_db.query.return_value = mock_query

    response = client.get("/receipts", headers=auth_headers)

    assert response.status_code == 200
    data = response.json()
    assert len(data) == 1
    assert data[0]['merchant_name'] == 'Walmart'


@patch('app.routers.receipts.get_db')
def test_get_receipts_empty(mock_get_db, client, mock_db, auth_headers):
    """Edge case: No receipts should return empty list"""
    mock_get_db.return_value = mock_db

    mock_query = Mock()
    mock_query.filter.return_value.order_by.return_value.limit.return_value.all.return_value = []
    mock_db.query.return_value = mock_query

    response = client.get("/receipts", headers=auth_headers)

    assert response.status_code == 200
    assert response.json() == []


@patch('app.routers.receipts.get_db')
def test_get_receipts_filter_unprocessed(mock_get_db, client, mock_db, auth_headers):
    """Full context: Filter only unprocessed receipts"""
    mock_get_db.return_value = mock_db

    mock_query = Mock()
    mock_query.filter.return_value = mock_query
    mock_query.order_by.return_value.limit.return_value.all.return_value = []
    mock_db.query.return_value = mock_query

    response = client.get("/receipts?include_processed=false", headers=auth_headers)

    assert response.status_code == 200


# ============================================================
# DELETE RECEIPT TESTS
# ============================================================


@patch('app.routers.receipts.get_db')
def test_delete_receipt_success(mock_get_db, client, mock_db, mock_user_id, sample_receipt_id, auth_headers):
    """Full context: Successfully delete receipt"""
    mock_get_db.return_value = mock_db

    mock_receipt = Mock()
    mock_receipt.id = uuid.UUID(sample_receipt_id)
    mock_receipt.user_id = uuid.UUID(mock_user_id)

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = mock_receipt
    mock_db.query.return_value = mock_query

    mock_db.delete = Mock()
    mock_db.commit = Mock()

    response = client.delete(f"/receipts/{sample_receipt_id}", headers=auth_headers)

    assert response.status_code == 200
    assert response.json()['status'] == 'success'
    mock_db.delete.assert_called_once_with(mock_receipt)


@patch('app.routers.receipts.get_db')
def test_delete_receipt_not_found(mock_get_db, client, mock_db, auth_headers):
    """Edge case: Delete non-existent receipt should return 404"""
    mock_get_db.return_value = mock_db

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = None
    mock_db.query.return_value = mock_query

    response = client.delete(f"/receipts/{uuid.uuid4()}", headers=auth_headers)

    assert response.status_code == 404


@patch('app.routers.receipts.get_db')
def test_delete_receipt_wrong_user(mock_get_db, client, mock_db, mock_user_id, sample_receipt_id, auth_headers):
    """Edge case: Delete other user's receipt should return 403"""
    mock_get_db.return_value = mock_db

    mock_receipt = Mock()
    mock_receipt.id = uuid.UUID(sample_receipt_id)
    mock_receipt.user_id = uuid.uuid4()  # Different user

    mock_query = Mock()
    mock_query.filter.return_value.first.return_value = mock_receipt
    mock_db.query.return_value = mock_query

    response = client.delete(f"/receipts/{sample_receipt_id}", headers=auth_headers)

    assert response.status_code == 403
