"""
test_routers_pantry_barcode.py

PURPOSE:
    Tests for the barcode lookup endpoint:
        GET /api/v1/pantry/barcode/{barcode}

    This endpoint is called by the mobile app when a barcode is scanned.
    It queries OpenFoodFacts (via BarcodeService) and returns product info.

HOW THESE TESTS WORK — the mocking pattern explained:

    The endpoint depends on BarcodeService.lookup(), which normally makes a
    real HTTP request to OpenFoodFacts. In tests we don't want to:
      - Hit the real internet (tests would be slow and flaky)
      - Depend on OpenFoodFacts having specific products in their DB

    So we use unittest.mock.patch() to replace BarcodeService.lookup with a
    fake function that immediately returns whatever data we tell it to.

    Example:
        with patch("app.routers.pantry.BarcodeService.lookup", return_value=MOCK_PRODUCT):
            response = test_client.get(...)

    This temporarily replaces BarcodeService.lookup (as seen by the router module)
    with a function that always returns MOCK_PRODUCT, runs the test, then restores
    the original function.

    WHY patch "app.routers.pantry.BarcodeService" and not "app.services.barcode.BarcodeService"?
        Python patches the name *where it is used*, not where it is defined.
        The router imports BarcodeService and uses it under the name
        "app.routers.pantry.BarcodeService", so that's the path we patch.

AUTH IN TESTS:
    The conftest.py has an autouse fixture (mock_supabase_token_validation) that
    automatically mocks Supabase's token verification for every test. This means
    our test JWT tokens (generated by generate_test_token) are accepted as valid.

    Tests that use auth_headers get a valid JWT token in the Authorization header.
    Tests without auth_headers get no token, which triggers a 403 response from
    the auth middleware.

FIXTURES USED (defined in conftest.py):
    test_client    — a FastAPI TestClient that makes real HTTP requests to our app
    auth_headers   — a dict like {"Authorization": "Bearer <test_token>"}
    sample_barcode — the string "8901234567890" (a valid EAN-13 barcode)
"""

import pytest
from fastapi import status
from unittest.mock import patch


# URL template — we substitute {barcode} in each test
BARCODE_URL = "/api/v1/pantry/barcode/{barcode}"

# ─────────────────────────────────────────────────────────────────────────────
# MOCK DATA
# This is what BarcodeService.lookup() returns when it finds a product.
# Mirrors the real OpenFoodFacts response structure that BarcodeService.lookup
# extracts and returns (see app/services/barcode.py).
# ─────────────────────────────────────────────────────────────────────────────
MOCK_PRODUCT = {
    "product_name": "Organic Whole Milk",
    "brands": "Horizon",
    "quantity": "1 gallon",
    "categories": "Dairy, Milk",
    "image_url": "https://images.openfoodfacts.org/milk.jpg",
    "ingredients_text": "Organic Grade A Milk",
    "nutriscore_grade": "b",
    "serving_size": "240mL",
    "packaging": "plastic jug",
    "barcode": "012345678901",
}


@pytest.mark.unit
@pytest.mark.barcode
class TestBarcodeLookup:
    """
    Integration-style tests for the GET /api/v1/pantry/barcode/{barcode} endpoint.

    These tests make real HTTP requests through the FastAPI app (using TestClient)
    but mock out the external BarcodeService so no real network calls are made.

    Each test covers one specific scenario that the endpoint must handle correctly.
    """

    def test_lookup_success(self, test_client, auth_headers, sample_barcode):
        """
        SCENARIO: Barcode exists in OpenFoodFacts.

        WHAT WE'RE CHECKING:
          - Status code is 200 OK
          - Response contains the product name from our mock data
          - Response contains the brand from our mock data
          - suggested_category is populated (BarcodeService.suggest_category ran)
          - The barcode from the URL is echoed back in the response

        HOW IT WORKS:
          We patch both BarcodeService.lookup (returns full product dict) and
          BarcodeService.suggest_category (returns "dairy") so the endpoint
          gets deterministic data and we can assert exact values.
        """
        with patch("app.routers.pantry.BarcodeService.lookup", return_value=MOCK_PRODUCT), \
             patch("app.routers.pantry.BarcodeService.suggest_category", return_value="dairy"):

            response = test_client.get(
                BARCODE_URL.format(barcode=sample_barcode),
                headers=auth_headers,
            )

        assert response.status_code == status.HTTP_200_OK
        data = response.json()
        assert data["product_name"] == "Organic Whole Milk"
        assert data["brands"] == "Horizon"
        assert data["suggested_category"] == "dairy"
        assert data["barcode"] == sample_barcode

    def test_lookup_product_not_found(self, test_client, auth_headers, sample_barcode):
        """
        SCENARIO: Barcode is valid format but not in OpenFoodFacts.

        BarcodeService.lookup returns None when the product isn't found.
        The endpoint should respond with 404 Not Found.

        WHY this matters: the mobile app catches a 404 and navigates to
        BarcodeResultScreen with product=null, allowing manual entry.
        """
        with patch("app.routers.pantry.BarcodeService.lookup", return_value=None):
            response = test_client.get(
                BARCODE_URL.format(barcode=sample_barcode),
                headers=auth_headers,
            )

        assert response.status_code == status.HTTP_404_NOT_FOUND
        # The word "not found" should appear in the error message
        assert "not found" in response.json()["detail"].lower()

    def test_lookup_service_error(self, test_client, auth_headers, sample_barcode):
        """
        SCENARIO: BarcodeService.lookup encountered a network/API error.

        When an error occurs, BarcodeService returns a dict with an "error" key
        instead of None. The endpoint checks for this and returns 500.

        This is different from "not found" (which returns None) because it means
        the lookup itself failed, not that the product doesn't exist.
        """
        with patch(
            "app.routers.pantry.BarcodeService.lookup",
            return_value={"error": "Barcode lookup timed out"},
        ):
            response = test_client.get(
                BARCODE_URL.format(barcode=sample_barcode),
                headers=auth_headers,
            )

        assert response.status_code == status.HTTP_500_INTERNAL_SERVER_ERROR
        # The error message from BarcodeService should be forwarded to the client
        assert "timed out" in response.json()["detail"]

    def test_lookup_unauthenticated(self, test_client, sample_barcode):
        """
        SCENARIO: Request has no Authorization header.

        The auth middleware rejects requests without a valid JWT token.
        NOTE: Our auth middleware returns 403 (Forbidden) for missing tokens,
        not 401 (Unauthorized). Both mean "you can't access this", but the
        middleware chose 403, so we accept either code here.

        WHY test this? Every protected endpoint should reject unauthenticated
        requests. This ensures the barcode route isn't accidentally left public.
        """
        # No auth_headers passed — request has no Authorization header
        response = test_client.get(BARCODE_URL.format(barcode=sample_barcode))

        # Auth middleware returns 403 for missing token
        assert response.status_code in (status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN)

    def test_lookup_null_product_name(self, test_client, auth_headers, sample_barcode):
        """
        SCENARIO: Product exists in OpenFoodFacts but has no name field.

        Some products in OpenFoodFacts are incomplete. The endpoint should still
        return 200 with product_name as null rather than crashing.

        HOW: We spread MOCK_PRODUCT and override product_name to None.
        The {**MOCK_PRODUCT, "product_name": None} syntax creates a copy of
        MOCK_PRODUCT with just that one field changed.
        """
        product_no_name = {**MOCK_PRODUCT, "product_name": None}

        with patch("app.routers.pantry.BarcodeService.lookup", return_value=product_no_name), \
             patch("app.routers.pantry.BarcodeService.suggest_category", return_value="pantry"):

            response = test_client.get(
                BARCODE_URL.format(barcode=sample_barcode),
                headers=auth_headers,
            )

        assert response.status_code == status.HTTP_200_OK
        # product_name should be null in the JSON, not cause a 500 error
        assert response.json()["product_name"] is None

    def test_lookup_category_suggestion_produce(self, test_client, auth_headers, sample_barcode):
        """
        SCENARIO: Product belongs to the produce category.

        Verifies that the suggest_category result is correctly returned in the
        response as suggested_category. The mobile app uses this to pre-fill
        the category chip selection on BarcodeResultScreen.
        """
        veggie_product = {
            **MOCK_PRODUCT,
            "product_name": "Baby Spinach",
            "categories": "vegetables, leafy greens",
        }

        with patch("app.routers.pantry.BarcodeService.lookup", return_value=veggie_product), \
             patch("app.routers.pantry.BarcodeService.suggest_category", return_value="produce"):

            response = test_client.get(
                BARCODE_URL.format(barcode=sample_barcode),
                headers=auth_headers,
            )

        assert response.status_code == status.HTTP_200_OK
        assert response.json()["suggested_category"] == "produce"

    def test_lookup_barcode_passed_through(self, test_client, auth_headers):
        """
        SCENARIO: A different barcode is used in the URL.

        The barcode from the URL path parameter should appear unchanged in the
        response body. This matters because the mobile app reads the barcode
        from the response to store it on the pantry item.
        """
        custom_barcode = "9780201379624"  # a real ISBN-13 formatted as EAN-13

        with patch("app.routers.pantry.BarcodeService.lookup", return_value=MOCK_PRODUCT), \
             patch("app.routers.pantry.BarcodeService.suggest_category", return_value="dairy"):

            response = test_client.get(
                BARCODE_URL.format(barcode=custom_barcode),
                headers=auth_headers,
            )

        assert response.status_code == status.HTTP_200_OK
        # The barcode in the response must match the one we sent, not the one in MOCK_PRODUCT
        assert response.json()["barcode"] == custom_barcode


@pytest.mark.unit
@pytest.mark.barcode
class TestBarcodeServiceUnit:
    """
    Pure unit tests for BarcodeService helper methods.

    These tests import BarcodeService directly and call its methods without
    going through the HTTP layer at all. No TestClient, no mocking needed —
    these are just function-call tests.

    WHY test these separately?
        suggest_category and parse_quantity_unit contain logic (regex, keyword
        matching) that can be tested exhaustively without any network or database.
        Keeping them as unit tests means they run instantly and don't depend on
        the rest of the app being set up correctly.
    """

    def test_suggest_category_dairy(self):
        """
        "Dairy products, Milk" in categories → should return "dairy".
        The keyword check is case-insensitive (BarcodeService lowercases the string).
        """
        from app.services.barcode import BarcodeService

        product = {"categories": "Dairy products, Milk"}
        assert BarcodeService.suggest_category(product) == "dairy"

    def test_suggest_category_produce(self):
        """
        "Fruits" in categories → should return "produce".
        The service maps both fruit and vegetable keywords to the "produce" category.
        """
        from app.services.barcode import BarcodeService

        product = {"categories": "Fruits, tropical fruits"}
        assert BarcodeService.suggest_category(product) == "produce"

    def test_suggest_category_protein(self):
        """
        "Meat products" in categories → should return "protein".
        """
        from app.services.barcode import BarcodeService

        product = {"categories": "Meat products, poultry"}
        assert BarcodeService.suggest_category(product) == "protein"

    def test_suggest_category_grains(self):
        """
        "Pasta" in categories → should return "grains".
        Bread, rice, cereal, oat, wheat, flour also map to grains.
        """
        from app.services.barcode import BarcodeService

        product = {"categories": "Pasta, dry goods"}
        assert BarcodeService.suggest_category(product) == "grains"

    def test_suggest_category_fallback_pantry(self):
        """
        "Snacks, chips" doesn't match any keyword → falls back to "pantry".
        The "pantry" category is the catch-all for anything unrecognized.
        """
        from app.services.barcode import BarcodeService

        product = {"categories": "Snacks, chips"}
        assert BarcodeService.suggest_category(product) == "pantry"

    def test_suggest_category_empty_categories(self):
        """
        Empty categories string → no keyword can match → fallback to "pantry".
        """
        from app.services.barcode import BarcodeService

        product = {"categories": ""}
        assert BarcodeService.suggest_category(product) == "pantry"

    def test_parse_quantity_unit_grams(self):
        """
        "500g" → quantity="500", unit="g".
        The regex matches digits + letters, then normalizes the unit abbreviation.
        """
        from app.services.barcode import BarcodeService

        result = BarcodeService.parse_quantity_unit("500g")
        assert result["quantity"] == "500"
        assert result["unit"] == "g"

    def test_parse_quantity_unit_liters(self):
        """
        "1 L" → quantity="1", unit="L".
        Handles a space between the number and unit.
        The service normalizes lowercase "l" to uppercase "L".
        """
        from app.services.barcode import BarcodeService

        result = BarcodeService.parse_quantity_unit("1 L")
        assert result["quantity"] == "1"
        assert result["unit"] == "L"

    def test_parse_quantity_unit_none(self):
        """
        None input → both fields should be None (not crash).
        Some products in OpenFoodFacts have no quantity field.
        """
        from app.services.barcode import BarcodeService

        result = BarcodeService.parse_quantity_unit(None)
        assert result["quantity"] is None
        assert result["unit"] is None

    def test_parse_quantity_unit_unrecognized(self):
        """
        "family size" → no regex match → returns the full string as quantity, unit=None.
        This graceful fallback means the UI can still display something useful.
        """
        from app.services.barcode import BarcodeService

        result = BarcodeService.parse_quantity_unit("family size")
        assert result["quantity"] == "family size"
        assert result["unit"] is None
